backend:
  name: git-gateway
  branch: main
media_folder: src/assets/uploads
public_folder: /assets/uploads

# Run "npx decap-server" for local backend
local_backend: true
editor:
  preview: false
i18n:
  structure: multiple_folders
  locales: [en-CA, fr-CA]
  default_locale: en-CA
collections:
  - label: Posts
    label_singular: Post
    name: post
    i18n: true
    folder: src/collections/posts/
    extension: md
    create: true
    fields:
      - {label: Title, name: title, widget: string, i18n: true}
      - {label: Excerpt, name: excerpt, widget: string, required: false, i18n: true}
      - {label: Author, name: author, widget: string, i18n: true}
      - {label: Publication Date, name: date, widget: datetime, i18n: duplicate}
      - {label: Body, name: body, widget: markdown, i18n: true}
  - label: Pages
    label_singular: Page
    name: page
    i18n: true
    folder: src/collections/pages/
    extension: md
    create: true
    filter: {field: layout, value: layouts/page}
    fields:
      - {label: Title, name: title, widget: string, i18n: true}
      - {label: Layout, name: layout, widget: hidden, i18n: duplicate, default: layouts/page}
      - {label: Navigation Order, name: order, widget: number, min: 0, i18n: duplicate}
      - {label: Navigation Label, name: key, widget: string, required: false, i18n: true}
      - {label: Excerpt, name: excerpt, widget: string, required: false, i18n: true}
      - {label: Body, name: body, widget: markdown, i18n: true}
  - label: Site Configuration
    name: config
    i18n: false
    files:
      - label: Site Configuration
        name: config
        file: src/_data/config.json
        fields:
          - {label: URL, name: url, widget: string}
          - {label: Maximum Posts in RSS Feed, name: maxPostsInFeed, widget: number, min: 1, i18n: false}
  - label: Site Data
    name: data
    i18n:
      structure: single_file
    files:
      - label: Site Data
        name: site
        file: src/_data/site.json
        i18n: true
        fields:
          - {label: Name, name: name, widget: string, i18n: true}
          - {label: Description, name: description, widget: text, i18n: true}
          - {label: Author Name, name: authorName, widget: string, i18n: true}
          - {label: Author Email, name: authorEmail, widget: string, i18n: duplicate}
          - {label: Author Website, name: authorWebsite, widget: string, i18n: duplicate}
