backend:
  name: github
  branch: main
  repo: fluid-project/trivet
  base_url: https://auth.incd.ca
  commit_messages:
    create: 'chore(cms): create "{{path}}"'
    update: 'chore(cms): update "{{path}}"'
    delete: 'chore(cms): delete "{{path}}"'
    uploadMedia: 'chore(cms): upload "{{path}}"'
    deleteMedia: 'chore(cms): delete "{{path}}"'
media_folder: src/assets/uploads
public_folder: /assets/uploads

i18n:
  locales: [en, fr]
  default_locale: en
  save_all_locales: false

collections:
  - label: Posts
    label_singular: Post
    name: post
    icon: article
    i18n:
      structure: multiple_folders
    folder: src/collections/posts/
    extension: md
    create: true
    sortable_fields:
      fields: [title, date]
      default:
        field: date
        direction: descending
    fields:
      - {label: Title, name: title, widget: string, i18n: true}
      - {label: UUID, name: uuid, widget: uuid, i18n: duplicate}
      - {label: Excerpt, name: excerpt, widget: string, required: false, i18n: true}
      - {label: Author, name: author, widget: string, i18n: true}
      - {label: Publication Date, name: date, widget: datetime, i18n: duplicate}
      - {label: Body, name: body, widget: markdown, i18n: true}
  - label: Pages
    label_singular: Page
    name: page
    icon: draft
    i18n:
      structure: multiple_folders
    folder: src/collections/pages/
    extension: md
    create: true
    filter: {field: layout, value: layouts/page}
    sortable_fields:
      fields: [title, order]
      default:
        field: order
        direction: ascending
    fields:
      - {label: Title, name: title, widget: string, i18n: true}
      - {label: UUID, name: uuid, widget: uuid, i18n: duplicate}
      - {label: Layout, name: layout, widget: hidden, i18n: duplicate, default: layouts/page}
      - {label: Navigation Order, name: order, widget: number, min: 0, i18n: duplicate}
      - {label: Navigation Label, name: key, widget: string, required: false, i18n: true}
      - {label: Excerpt, name: excerpt, widget: string, required: false, i18n: true}
      - {label: Body, name: body, widget: markdown, i18n: true}

singletons:
  - label: Configuration
    name: config
    icon: settings
    editor:
      preview: false
    file: src/_data/config.json
    i18n: false
    fields:
      - {label: URL, name: url, widget: string}
      - {label: Maximum Posts in RSS Feed, name: maxPostsInFeed, widget: number, min: 1, i18n: false}
  - label: Site Data
    name: site
    icon: code
    editor:
      preview: false
    file: src/_data/site.json
    i18n: true
    fields:
      - {label: Name, name: name, widget: string, i18n: true}
      - {label: Description, name: description, widget: text, i18n: true}
      - {label: Author Name, name: authorName, widget: string, i18n: true}
      - {label: Author Email, name: authorEmail, widget: string, i18n: duplicate}
      - {label: Author Website, name: authorWebsite, widget: string, i18n: duplicate}
